using System;

namespace NET1.S._2019.Tsyvis._23.Matrices
{
    /// <summary>
    /// Provide manipulation with square matrix.
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// <seealso cref="NET1.S._2019.Tsyvis._23.Matrices.Matrix{T}" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for SquareMatrix`1
    public class SquareMatrix<T> : Matrix<T>
        where T : struct
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SquareMatrix{T}"/> class.
        /// </summary>
        /// <param name="array">The array.</param>
        /// <exception cref="ArgumentException">Array is not a square matrix</exception>
        public SquareMatrix(T[,] array)
            : base(array)
        {
            if (array.GetLength(0) != array.GetLength(1))
            {
                throw new ArgumentException("Array is not a square matrix");
            }
        }
    }
}
